base_model: meta-llama/Llama-2-13b-hf
base_model_config: meta-llama/Llama-2-13b-hf
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: ./custom/mingus/mingus_dataset_v5.jsonl
    ds_type: json # see other options below
    type: mingus.load_mingus

dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: ./qlora-out-mingus-13b-v4

adapter: qlora
lora_model_dir:

sequence_len: 4096
sample_packing: true

lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
  - v_proj
  - gate_proj
  - k_proj
  - down_proj
  - up_proj
  - o_proj
  - q_proj
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: mingus
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 1
num_epochs: 1
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: true

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 20
save_steps: 50
debug:
deepspeed:
weight_decay: 0.1
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
